  CREATE TABLE "JKRAJPOP"."APPOINTMENT" 
   (	"CUSTOMERID" VARCHAR2(20 BYTE), 
	"LICENSEPLATE" VARCHAR2(10 BYTE), 
	"SERVICECENTERID" VARCHAR2(20 BYTE), 
	"SERVICETYPE" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into JKRAJPOP.APPOINTMENT
SET DEFINE OFF;




  CREATE TABLE "JKRAJPOP"."CARS" 
   (	"LICENSEPLATE" VARCHAR2(10 BYTE), 
	"MAKE" VARCHAR2(20 BYTE), 
	"MODEL" VARCHAR2(10 BYTE), 
	"YEAR" NUMBER(*,0), 
	"DATEOFRECENTSERVICE" DATE, 
	"DATEOFPURCHASE" DATE, 
	"MILEAGE" NUMBER(*,0), 
	"TYPEOFRECENTSERVICE" VARCHAR2(1 BYTE), 
	"CUSTOMERID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into JKRAJPOP.CARS
SET DEFINE OFF;
  CREATE UNIQUE INDEX "JKRAJPOP"."SYS_C00503656" ON "JKRAJPOP"."CARS" ("LICENSEPLATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  ALTER TABLE "JKRAJPOP"."CARS" ADD PRIMARY KEY ("LICENSEPLATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "JKRAJPOP"."CARS" MODIFY ("CUSTOMERID" NOT NULL ENABLE);



  CREATE TABLE "JKRAJPOP"."CUSTOMER" 
   (	"NAME" VARCHAR2(255 BYTE), 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"PHONENUMBER" NUMBER, 
	"EMAIL" VARCHAR2(40 BYTE), 
	"SERVICECENTERID" VARCHAR2(20 BYTE), 
	"CUSTOMERID" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into JKRAJPOP.CUSTOMER
SET DEFINE OFF;
  CREATE UNIQUE INDEX "JKRAJPOP"."CUSTOMER_PK" ON "JKRAJPOP"."CUSTOMER" ("CUSTOMERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  ALTER TABLE "JKRAJPOP"."CUSTOMER" ADD CONSTRAINT "CUSTOMER_PK" PRIMARY KEY ("CUSTOMERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "JKRAJPOP"."CUSTOMER" MODIFY ("CUSTOMERID" NOT NULL ENABLE);
 
  ALTER TABLE "JKRAJPOP"."CUSTOMER" MODIFY ("PASSWORD" NOT NULL ENABLE);



  CREATE TABLE "JKRAJPOP"."DIAGNOSTIC" 
   (	"DG_ID" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"FEE" NUMBER, 
	"SERVICE1" VARCHAR2(20 BYTE), 
	"SERVICE2" VARCHAR2(20 BYTE), 
	"SERVICE3" VARCHAR2(20 BYTE), 
	"SERVICE4" VARCHAR2(20 BYTE), 
	"ISSUE" VARCHAR2(50 BYTE), 
	"MAKE" VARCHAR2(20 BYTE), 
	"MODEL" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into JKRAJPOP.DIAGNOSTIC
SET DEFINE OFF;
  CREATE UNIQUE INDEX "JKRAJPOP"."DIAGNOSTIC_PK" ON "JKRAJPOP"."DIAGNOSTIC" ("DG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  ALTER TABLE "JKRAJPOP"."DIAGNOSTIC" ADD CONSTRAINT "DIAGNOSTIC_PK" PRIMARY KEY ("DG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "JKRAJPOP"."DIAGNOSTIC" MODIFY ("DG_ID" NOT NULL ENABLE);
 
  ALTER TABLE "JKRAJPOP"."DIAGNOSTIC" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "JKRAJPOP"."DIAGNOSTIC" MODIFY ("FEE" NOT NULL ENABLE);
 
  ALTER TABLE "JKRAJPOP"."DIAGNOSTIC" MODIFY ("ISSUE" NOT NULL ENABLE);
 
  ALTER TABLE "JKRAJPOP"."DIAGNOSTIC" MODIFY ("MAKE" NOT NULL ENABLE);
 
  ALTER TABLE "JKRAJPOP"."DIAGNOSTIC" MODIFY ("MODEL" NOT NULL ENABLE);



  CREATE TABLE "JKRAJPOP"."DISTRIBUTOR" 
   (	"DID" VARCHAR2(20 BYTE), 
	"IID" VARCHAR2(20 BYTE), 
	"PARTID" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into JKRAJPOP.DISTRIBUTOR
SET DEFINE OFF;
  CREATE UNIQUE INDEX "JKRAJPOP"."SYS_C00485792" ON "JKRAJPOP"."DISTRIBUTOR" ("DID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  ALTER TABLE "JKRAJPOP"."DISTRIBUTOR" ADD PRIMARY KEY ("DID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;



  CREATE TABLE "JKRAJPOP"."EMPLOYEE" 
   (	"EMPLOYEEID" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(255 BYTE), 
	"PHONENUMBER" NUMBER(*,0), 
	"EMAILADDRESS" VARCHAR2(40 BYTE), 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"POSITION" VARCHAR2(1 BYTE), 
	"SERVICECENTERID" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into JKRAJPOP.EMPLOYEE
SET DEFINE OFF;
  CREATE UNIQUE INDEX "JKRAJPOP"."EMPLOYEE_PK" ON "JKRAJPOP"."EMPLOYEE" ("EMPLOYEEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  ALTER TABLE "JKRAJPOP"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_PK" PRIMARY KEY ("EMPLOYEEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "JKRAJPOP"."EMPLOYEE" MODIFY ("EMPLOYEEID" NOT NULL ENABLE);
 
  ALTER TABLE "JKRAJPOP"."EMPLOYEE" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "JKRAJPOP"."EMPLOYEE" MODIFY ("PASSWORD" NOT NULL ENABLE);
 
  ALTER TABLE "JKRAJPOP"."EMPLOYEE" MODIFY ("SERVICECENTERID" NOT NULL ENABLE);



  CREATE TABLE "JKRAJPOP"."INVENTORY" 
   (	"IID" VARCHAR2(20 BYTE), 
	"SERVICECENTERID" VARCHAR2(20 BYTE), 
	"CURRENTQ" NUMBER(*,0), 
	"MINTHRESHOLD" NUMBER(*,0), 
	"MINQUANTITY" NUMBER(*,0), 
	"D1" NUMBER(*,0), 
	"D2" NUMBER(*,0), 
	"PARTID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into JKRAJPOP.INVENTORY
SET DEFINE OFF;
  CREATE UNIQUE INDEX "JKRAJPOP"."INVENTORY_PK" ON "JKRAJPOP"."INVENTORY" ("IID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  ALTER TABLE "JKRAJPOP"."INVENTORY" ADD CONSTRAINT "INVENTORY_PK" PRIMARY KEY ("IID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "JKRAJPOP"."INVENTORY" MODIFY ("IID" NOT NULL ENABLE);
 
  ALTER TABLE "JKRAJPOP"."INVENTORY" MODIFY ("SERVICECENTERID" NOT NULL ENABLE);



  CREATE TABLE "JKRAJPOP"."MAINTENANCE" 
   (	"MAINTENANCEID" VARCHAR2(20 BYTE), 
	"MAKE" VARCHAR2(20 BYTE), 
	"MODEL" VARCHAR2(10 BYTE), 
	"MILES" NUMBER, 
	"SERVICE1" VARCHAR2(20 BYTE), 
	"SERVICE2" VARCHAR2(20 BYTE), 
	"SERVICE3" VARCHAR2(20 BYTE), 
	"SERVICE4" VARCHAR2(20 BYTE), 
	"SERVICE5" VARCHAR2(20 BYTE), 
	"SERVICE6" VARCHAR2(20 BYTE), 
	"MAINTENANCETYPE" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into JKRAJPOP.MAINTENANCE
SET DEFINE OFF;
  CREATE UNIQUE INDEX "JKRAJPOP"."MAINTENANCE_PK" ON "JKRAJPOP"."MAINTENANCE" ("MAINTENANCEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  ALTER TABLE "JKRAJPOP"."MAINTENANCE" ADD CONSTRAINT "MAINTENANCE_PK" PRIMARY KEY ("MAINTENANCEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "JKRAJPOP"."MAINTENANCE" MODIFY ("MAINTENANCEID" NOT NULL ENABLE);
 
  ALTER TABLE "JKRAJPOP"."MAINTENANCE" MODIFY ("MAKE" NOT NULL ENABLE);
 
  ALTER TABLE "JKRAJPOP"."MAINTENANCE" MODIFY ("MODEL" NOT NULL ENABLE);
 
  ALTER TABLE "JKRAJPOP"."MAINTENANCE" MODIFY ("MILES" NOT NULL ENABLE);
 
  ALTER TABLE "JKRAJPOP"."MAINTENANCE" MODIFY ("MAINTENANCETYPE" NOT NULL ENABLE);



  CREATE TABLE "JKRAJPOP"."NOTIFICATION" 
   (	"SERVICECENTERID" VARCHAR2(20 BYTE), 
	"NOTIFICATIONDATE" DATE, 
	"MESSAGE" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into JKRAJPOP.NOTIFICATION
SET DEFINE OFF;



  CREATE TABLE "JKRAJPOP"."ORDERS" 
   (	"ORDERID" VARCHAR2(20 BYTE), 
	"PARTID" VARCHAR2(20 BYTE), 
	"EXPECTEDDELIVERY" DATE, 
	"ACTUALDELIVERY" DATE, 
	"QUANTITY" NUMBER(*,0), 
	"DESTINATION" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"ORDERPLACEMENT" DATE, 
	"ORIGIN" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into JKRAJPOP.ORDERS
SET DEFINE OFF;
  CREATE UNIQUE INDEX "JKRAJPOP"."SYS_C00485790" ON "JKRAJPOP"."ORDERS" ("ORDERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE OR REPLACE TRIGGER "JKRAJPOP"."ORDERS_TRG" 
BEFORE INSERT ON ORDERS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ORDERID IS NULL THEN
      SELECT ORDERS_SEQ.NEXTVAL INTO :NEW.ORDERID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "JKRAJPOP"."ORDERS_TRG" ENABLE;
  ALTER TABLE "JKRAJPOP"."ORDERS" ADD PRIMARY KEY ("ORDERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;



  CREATE TABLE "JKRAJPOP"."PARTS" 
   (	"PARTID" VARCHAR2(20 BYTE), 
	"PARTNAME" VARCHAR2(255 BYTE), 
	"MAKE" VARCHAR2(20 BYTE), 
	"PRICE" NUMBER(*,0), 
	"WARRANTY" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into JKRAJPOP.PARTS
SET DEFINE OFF;
  CREATE UNIQUE INDEX "JKRAJPOP"."SYS_C00485788" ON "JKRAJPOP"."PARTS" ("PARTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  ALTER TABLE "JKRAJPOP"."PARTS" ADD PRIMARY KEY ("PARTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "JKRAJPOP"."PARTS" MODIFY ("PARTNAME" NOT NULL ENABLE);
 
  ALTER TABLE "JKRAJPOP"."PARTS" MODIFY ("MAKE" NOT NULL ENABLE);
 
  ALTER TABLE "JKRAJPOP"."PARTS" MODIFY ("PRICE" NOT NULL ENABLE);



  CREATE TABLE "JKRAJPOP"."PAYROLL" 
   (	"FREQUENCY" VARCHAR2(20 BYTE), 
	"STARTDATE" DATE, 
	"WAGES" NUMBER(*,0), 
	"EMPLOYEEID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into JKRAJPOP.PAYROLL
SET DEFINE OFF;



  CREATE TABLE "JKRAJPOP"."SERVICE" 
   (	"SERVICEID" VARCHAR2(20 BYTE), 
	"CHARGERATE" NUMBER(*,0), 
	"TIME" FLOAT(126), 
	"MAKE" VARCHAR2(20 BYTE), 
	"MODEL" VARCHAR2(10 BYTE), 
	"QUANTITY" NUMBER(*,0), 
	"PARTID" VARCHAR2(20 BYTE), 
	"SERVICENAME" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into JKRAJPOP.SERVICE
SET DEFINE OFF;
  CREATE UNIQUE INDEX "JKRAJPOP"."REPAIRS_PK" ON "JKRAJPOP"."SERVICE" ("SERVICEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  ALTER TABLE "JKRAJPOP"."SERVICE" ADD CONSTRAINT "REPAIRS_PK" PRIMARY KEY ("SERVICEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "JKRAJPOP"."SERVICE" MODIFY ("SERVICEID" NOT NULL ENABLE);
 
  ALTER TABLE "JKRAJPOP"."SERVICE" MODIFY ("MAKE" NOT NULL ENABLE);
 
  ALTER TABLE "JKRAJPOP"."SERVICE" MODIFY ("MODEL" NOT NULL ENABLE);
 
  ALTER TABLE "JKRAJPOP"."SERVICE" MODIFY ("QUANTITY" NOT NULL ENABLE);



  CREATE TABLE "JKRAJPOP"."SERVICECENTER" 
   (	"ADDRESS" VARCHAR2(255 BYTE), 
	"SERVICECENTERID" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(255 BYTE), 
	"TELNO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into JKRAJPOP.SERVICECENTER
SET DEFINE OFF;
  CREATE UNIQUE INDEX "JKRAJPOP"."SERVICECENTER_PK" ON "JKRAJPOP"."SERVICECENTER" ("SERVICECENTERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  ALTER TABLE "JKRAJPOP"."SERVICECENTER" ADD CONSTRAINT "SERVICECENTER_PK" PRIMARY KEY ("SERVICECENTERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "JKRAJPOP"."SERVICECENTER" MODIFY ("ADDRESS" NOT NULL ENABLE);
 
  ALTER TABLE "JKRAJPOP"."SERVICECENTER" MODIFY ("SERVICECENTERID" NOT NULL ENABLE);
 
  ALTER TABLE "JKRAJPOP"."SERVICECENTER" MODIFY ("NAME" NOT NULL ENABLE);



  CREATE TABLE "JKRAJPOP"."SERVICEHISTORY" 
   (	"CUSTOMERID" VARCHAR2(20 BYTE), 
	"LICENSEPLATE" VARCHAR2(20 BYTE), 
	"SERVICEDATE" DATE, 
	"TYPEOFSERVICE" VARCHAR2(200 BYTE), 
	"STARTTIME" VARCHAR2(20 BYTE), 
	"ENDTIME" VARCHAR2(20 BYTE), 
	"MECHANICNAME" VARCHAR2(20 BYTE), 
	"SENDDATE" DATE, 
	"SERVICEHISTORY" NUMBER, 
	"DIAGNOSIS" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into JKRAJPOP.SERVICEHISTORY
SET DEFINE OFF;
  CREATE UNIQUE INDEX "JKRAJPOP"."SERVICEHISTORY_PK1" ON "JKRAJPOP"."SERVICEHISTORY" ("SERVICEHISTORY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  ALTER TABLE "JKRAJPOP"."SERVICEHISTORY" ADD CONSTRAINT "SERVICEHISTORY_PK" PRIMARY KEY ("SERVICEHISTORY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "JKRAJPOP"."SERVICEHISTORY" MODIFY ("CUSTOMERID" NOT NULL ENABLE);
 
  ALTER TABLE "JKRAJPOP"."SERVICEHISTORY" MODIFY ("LICENSEPLATE" NOT NULL ENABLE);
 
  ALTER TABLE "JKRAJPOP"."SERVICEHISTORY" MODIFY ("SERVICEHISTORY" NOT NULL ENABLE);



  CREATE TABLE "JKRAJPOP"."TIMESLOT" 
   (	"SERVICECENTERID" VARCHAR2(20 BYTE), 
	"DAY" VARCHAR2(20 BYTE), 
	"T8#8_30" NUMBER(*,0), 
	"T8_30#9" NUMBER(*,0), 
	"T9#9_30" NUMBER(*,0), 
	"T9_30#10" NUMBER(*,0), 
	"T10#10_30" NUMBER(*,0), 
	"T10_30#11" NUMBER(*,0), 
	"T11#11_30" NUMBER(*,0), 
	"T11_30#12" NUMBER(*,0), 
	"T12#12_30" NUMBER(*,0), 
	"T12_30#1" NUMBER(*,0), 
	"T1#1_30" NUMBER(*,0), 
	"T1_30#2" NUMBER(*,0), 
	"T2#2_30" NUMBER(*,0), 
	"T2_30#3" NUMBER(*,0), 
	"T3#3_30" NUMBER(*,0), 
	"T3_30#4" NUMBER(*,0), 
	"T4#4_30" NUMBER(*,0), 
	"T4_30#5" NUMBER(*,0), 
	"T5#5_30" NUMBER(*,0), 
	"T5_30#6" NUMBER(*,0), 
	"T6#6_30" NUMBER(*,0), 
	"T6_30#7" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into JKRAJPOP.TIMESLOT
SET DEFINE OFF;
