--------------------------------------------------------
--  File created - Tuesday-November-20-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SERVICE
--------------------------------------------------------

  CREATE TABLE "JKRAJPOP"."SERVICE" 
   (	"SERVICEID" VARCHAR2(20 BYTE), 
	"CHARGERATE" NUMBER(*,0), 
	"TIME" FLOAT(126), 
	"MAKE" VARCHAR2(20 BYTE), 
	"MODEL" VARCHAR2(10 BYTE), 
	"QUANTITY" NUMBER(*,0), 
	"PARTID" VARCHAR2(20 BYTE), 
	"SERVICENAME" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into JKRAJPOP.SERVICE
SET DEFINE OFF;
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('74',65,1,'Toyota','Prius',4,'40','Piston Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('75',65,1,'Honda','Civic',4,'41','Piston Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('76',65,1,'Honda','Accord',4,'41','Piston Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('77',65,1,'Nissan','Altima',6,'42','Piston Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('78',65,1,'Nissan','Rogue',8,'42','Piston Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('79',50,0.25,'Toyota','Corolla',1,'43','Power Steering Check');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('80',50,0.25,'Toyota','Prius',1,'43','Power Steering Check');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('81',50,0.25,'Honda','Civic',1,'44','Power Steering Check');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('82',50,0.25,'Honda','Accord',1,'44','Power Steering Check');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('83',50,0.25,'Nissan','Altima',1,'45','Power Steering Check');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('84',50,0.25,'Nissan','Rogue',1,'45','Power Steering Check');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('73',65,1,'Toyota','Corolla',4,'40','Piston Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('61',50,0.5,'Toyota','Corolla',2,'34','Headlights Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('62',50,0.5,'Toyota','Prius',2,'34','Headlights Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('63',50,0.5,'Honda','Civic',2,'35','Headlights Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('64',50,0.5,'Honda','Accord',2,'35','Headlights Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('65',50,0.5,'Nissan','Altima',2,'36','Headlights Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('66',50,0.5,'Nissan','Rogue',2,'36','Headlights Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('67',50,0.25,'Toyota','Corolla',1,'37','Oil Filter Change');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('68',50,0.25,'Toyota','Prius',1,'37','Oil Filter Change');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('69',50,0.25,'Honda','Civic',1,'38','Oil Filter Change');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('70',50,0.25,'Honda','Accord',1,'38','Oil Filter Change');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('71',50,0.25,'Nissan','Altima',1,'39','Oil Filter Change');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('72',50,0.25,'Nissan','Rogue',2,'39','Oil Filter Change');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('85',50,0.25,'Toyota','Corolla',4,'46','Spark Plugs Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('86',50,0.25,'Toyota','Prius',4,'46','Spark Plugs Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('87',50,0.25,'Honda','Civic',4,'47','Spark Plugs Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('88',50,0.25,'Honda','Accord',4,'47','Spark Plugs Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('89',50,0.25,'Nissan','Altima',6,'48','Spark Plugs Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('90',50,0.25,'Nissan','Rogue',8,'48','Spark Plugs Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('91',50,0.25,'Toyota','Corolla',1,'49','Suspension Check');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('92',50,0.25,'Toyota','Prius',1,'49','Suspension Check');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('93',50,0.25,'Honda','Civic',1,'50','Suspension Check');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('94',50,0.25,'Honda','Accord',1,'50','Suspension Check');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('95',50,0.25,'Nissan','Altima',1,'51','Suspension Check');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('96',50,0.25,'Nissan','Rogue',1,'51','Suspension Check');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('97',50,0.5,'Toyota','Corolla',2,'34','Tail Lights Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('98',50,0.5,'Toyota','Prius',2,'34','Tail Lights Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('99',50,0.5,'Honda','Civic',2,'35','Tail Lights Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('100',50,0.5,'Honda','Accord',2,'35','Tail Lights Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('101',50,0.5,'Nissan','Altima',2,'36','Tail Lights Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('102',50,0.5,'Nissan','Rogue',2,'36','Tail Lights Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('103',50,0.5,'Toyota','Corolla',4,'34','Turn Lights Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('104',50,0.5,'Toyota','Prius',4,'34','Turn Lights Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('105',50,0.5,'Honda','Civic',4,'35','Turn Lights Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('106',50,0.5,'Honda','Accord',4,'35','Turn Lights Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('107',50,0.5,'Nissan','Altima',4,'36','Turn Lights Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('108',50,0.5,'Nissan','Rogue',4,'36','Turn Lights Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('109',65,1,'Toyota','Corolla',4,'52','Valve Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('110',65,1,'Toyota','Prius',4,'52','Valve Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('111',65,1,'Honda','Civic',4,'53','Valve Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('112',65,1,'Honda','Accord',4,'53','Valve Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('113',65,1,'Nissan','Altima',6,'54','Valve Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('114',65,1,'Nissan','Rogue',8,'54','Valve Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('115',65,1,'Toyota','Corolla',2,null,'Wheel Alignment');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('116',65,1,'Toyota','Prius',2,null,'Wheel Alignment');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('117',65,1,'Honda','Civic',2,null,'Wheel Alignment');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('118',65,1,'Honda','Accord',2,null,'Wheel Alignment');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('119',65,1,'Nissan','Altima',2,null,'Wheel Alignment');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('120',65,1,'Nissan','Rogue',2,null,'Wheel Alignment');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('121',50,0.25,'Toyota','Corolla',1,'55','Wiper Check');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('122',50,0.25,'Toyota','Prius',1,'55','Wiper Check');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('123',50,0.25,'Honda','Civic',1,'56','Wiper Check');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('124',50,0.25,'Honda','Accord',1,'56','Wiper Check');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('125',50,0.25,'Nissan','Altima',1,'57','Wiper Check');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('126',50,0.25,'Nissan','Rogue',1,'57','Wiper Check');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('1',50,0.25,'Toyota','Corolla',1,'1','Air Filter Change');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('2',50,0.25,'Toyota','Prius',1,'1','Air Filter Change');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('3',50,0.25,'Honda','Civic',1,'2','Air Filter Change');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('4',50,0.25,'Honda','Accord',2,'2','Air Filter Change');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('5',50,0.25,'Nissan','Altima',1,'3','Air Filter Change');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('6',50,0.25,'Nissan','Rogue',3,'3','Air Filter Change');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('7',50,0.25,'Toyota','Corolla',1,'7','Battery Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('8',50,0.25,'Toyota','Prius',1,'7','Battery Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('9',50,0.25,'Honda','Civic',1,'8','Battery Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('10',50,0.25,'Honda','Accord',1,'8','Battery Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('11',50,0.25,'Nissan','Altima',1,'9','Battery Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('12',50,0.25,'Nissan','Rogue',2,'9','Battery Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('13',50,0.25,'Toyota','Corolla',1,'10','Brake Check');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('14',50,0.25,'Toyota','Prius',1,'10','Brake Check');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('15',50,0.25,'Honda','Civic',1,'11','Brake Check');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('16',50,0.25,'Honda','Accord',1,'11','Brake Check');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('17',50,0.25,'Nissan','Altima',1,'12','Brake Check');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('18',50,0.25,'Nissan','Rogue',2,'12','Brake Check');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('19',50,0.5,'Toyota','Corolla',4,'13','Brake Repair');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('20',50,0.5,'Toyota','Prius',4,'13','Brake Repair');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('21',50,0.5,'Honda','Civic',4,'14','Brake Repair');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('22',50,0.5,'Honda','Accord',4,'14','Brake Repair');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('23',50,0.5,'Nissan','Altima',4,'15','Brake Repair');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('24',50,0.5,'Nissan','Rogue',4,'15','Brake Repair');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('25',65,1,'Toyota','Corolla',1,'16','Camshaft Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('26',65,1,'Toyota','Prius',1,'16','Camshaft Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('27',65,1,'Honda','Civic',1,'17','Camshaft Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('28',65,1,'Honda','Accord',1,'17','Camshaft Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('29',65,1,'Nissan','Altima',1,'18','Camshaft Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('30',65,1,'Nissan','Rogue',2,'18','Camshaft Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('31',65,1,'Toyota','Corolla',1,'19','Catalytic Converter Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('32',65,1,'Toyota','Prius',1,'19','Catalytic Converter Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('33',65,1,'Honda','Civic',1,'20','Catalytic Converter Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('34',65,1,'Honda','Accord',1,'20','Catalytic Converter Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('35',65,1,'Nissan','Altima',1,'21','Catalytic Converter Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('36',65,1,'Nissan','Rogue',1,'21','Catalytic Converter Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('37',50,0.25,'Toyota','Corolla',1,'22','Coolant Recycle');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('38',50,0.25,'Toyota','Prius',1,'22','Coolant Recycle');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('39',50,0.25,'Honda','Civic',1,'23','Coolant Recycle');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('40',50,0.25,'Honda','Accord',1,'23','Coolant Recycle');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('41',50,0.25,'Nissan','Altima',2,'24','Coolant Recycle');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('42',50,0.25,'Nissan','Rogue',2,'24','Coolant Recycle');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('43',65,1,'Toyota','Corolla',1,'25','Drive Belt Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('44',65,1,'Toyota','Prius',1,'25','Drive Belt Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('45',65,1,'Honda','Civic',1,'26','Drive Belt Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('46',65,1,'Honda','Accord',1,'26','Drive Belt Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('47',65,1,'Nissan','Altima',1,'27','Drive Belt Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('48',65,1,'Nissan','Rogue',1,'27','Drive Belt Replacement');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('49',50,0.25,'Toyota','Corolla',1,'28','Engine Oil Change');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('50',50,0.25,'Toyota','Prius',1,'28','Engine Oil Change');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('51',50,0.25,'Honda','Civic',1,'29','Engine Oil Change');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('52',50,0.25,'Honda','Accord',1,'29','Engine Oil Change');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('53',50,0.25,'Nissan','Altima',2,'30','Engine Oil Change');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('54',50,0.25,'Nissan','Rogue',3,'30','Engine Oil Change');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('55',65,1,'Toyota','Corolla',6,'31','Gearbox Repair');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('56',65,1,'Toyota','Prius',6,'31','Gearbox Repair');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('57',65,1,'Honda','Civic',12,'32','Gearbox Repair');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('58',65,1,'Honda','Accord',7,'32','Gearbox Repair');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('59',65,1,'Nissan','Altima',7,'33','Gearbox Repair');
Insert into JKRAJPOP.SERVICE (SERVICEID,CHARGERATE,TIME,MAKE,MODEL,QUANTITY,PARTID,SERVICENAME) values ('60',65,1,'Nissan','Rogue',9,'33','Gearbox Repair');
--------------------------------------------------------
--  DDL for Index REPAIRS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JKRAJPOP"."REPAIRS_PK" ON "JKRAJPOP"."SERVICE" ("SERVICEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SERVICE
--------------------------------------------------------

  ALTER TABLE "JKRAJPOP"."SERVICE" ADD CONSTRAINT "REPAIRS_PK" PRIMARY KEY ("SERVICEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "JKRAJPOP"."SERVICE" MODIFY ("SERVICEID" NOT NULL ENABLE);
 
  ALTER TABLE "JKRAJPOP"."SERVICE" MODIFY ("MAKE" NOT NULL ENABLE);
 
  ALTER TABLE "JKRAJPOP"."SERVICE" MODIFY ("MODEL" NOT NULL ENABLE);
 
  ALTER TABLE "JKRAJPOP"."SERVICE" MODIFY ("QUANTITY" NOT NULL ENABLE);
