--------------------------------------------------------
--  File created - Tuesday-November-20-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DISTRIBUTOR
--------------------------------------------------------

  CREATE TABLE "JKRAJPOP"."DISTRIBUTOR" 
   (	"DID" VARCHAR2(20 BYTE), 
	"IID" VARCHAR2(20 BYTE), 
	"PARTID" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into JKRAJPOP.DISTRIBUTOR
SET DEFINE OFF;
Insert into JKRAJPOP.DISTRIBUTOR (DID,IID,PARTID,NAME) values ('D0001',null,null,'D1');
Insert into JKRAJPOP.DISTRIBUTOR (DID,IID,PARTID,NAME) values ('D0002',null,null,'D2');
--------------------------------------------------------
--  DDL for Index SYS_C00485792
--------------------------------------------------------

  CREATE UNIQUE INDEX "JKRAJPOP"."SYS_C00485792" ON "JKRAJPOP"."DISTRIBUTOR" ("DID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DISTRIBUTOR
--------------------------------------------------------

  ALTER TABLE "JKRAJPOP"."DISTRIBUTOR" ADD PRIMARY KEY ("DID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
