--------------------------------------------------------
--  File created - Tuesday-November-20-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MAINTENANCE
--------------------------------------------------------

  CREATE TABLE "JKRAJPOP"."MAINTENANCE" 
   (	"MAINTENANCEID" VARCHAR2(20 BYTE), 
	"MAKE" VARCHAR2(20 BYTE), 
	"MODEL" VARCHAR2(10 BYTE), 
	"MILES" NUMBER, 
	"SERVICE1" VARCHAR2(20 BYTE), 
	"SERVICE2" VARCHAR2(20 BYTE), 
	"SERVICE3" VARCHAR2(20 BYTE), 
	"SERVICE4" VARCHAR2(20 BYTE), 
	"SERVICE5" VARCHAR2(20 BYTE), 
	"SERVICE6" VARCHAR2(20 BYTE), 
	"MAINTENANCETYPE" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into JKRAJPOP.MAINTENANCE
SET DEFINE OFF;
Insert into JKRAJPOP.MAINTENANCE (MAINTENANCEID,MAKE,MODEL,MILES,SERVICE1,SERVICE2,SERVICE3,SERVICE4,SERVICE5,SERVICE6,MAINTENANCETYPE) values ('M0001','Toyota','Corolla',5000,'49','37',null,null,null,null,'A');
Insert into JKRAJPOP.MAINTENANCE (MAINTENANCEID,MAKE,MODEL,MILES,SERVICE1,SERVICE2,SERVICE3,SERVICE4,SERVICE5,SERVICE6,MAINTENANCETYPE) values ('M0002','Toyota','Corolla',25000,'1','67','13','121','85',null,'B');
Insert into JKRAJPOP.MAINTENANCE (MAINTENANCEID,MAKE,MODEL,MILES,SERVICE1,SERVICE2,SERVICE3,SERVICE4,SERVICE5,SERVICE6,MAINTENANCETYPE) values ('M0003','Toyota','Corolla',45000,'91','19','79',null,null,null,'C');
Insert into JKRAJPOP.MAINTENANCE (MAINTENANCEID,MAKE,MODEL,MILES,SERVICE1,SERVICE2,SERVICE3,SERVICE4,SERVICE5,SERVICE6,MAINTENANCETYPE) values ('M0004','Toyota','Prius',10000,'50','68','38',null,null,null,'A');
Insert into JKRAJPOP.MAINTENANCE (MAINTENANCEID,MAKE,MODEL,MILES,SERVICE1,SERVICE2,SERVICE3,SERVICE4,SERVICE5,SERVICE6,MAINTENANCETYPE) values ('M0005','Toyota','Prius',28000,'2','14','122','86','8',null,'B');
Insert into JKRAJPOP.MAINTENANCE (MAINTENANCEID,MAKE,MODEL,MILES,SERVICE1,SERVICE2,SERVICE3,SERVICE4,SERVICE5,SERVICE6,MAINTENANCETYPE) values ('M0006','Toyota','Prius',58000,'92','20','80',null,null,null,'C');
Insert into JKRAJPOP.MAINTENANCE (MAINTENANCEID,MAKE,MODEL,MILES,SERVICE1,SERVICE2,SERVICE3,SERVICE4,SERVICE5,SERVICE6,MAINTENANCETYPE) values ('M0007','Nissan','Altima',10000,'53','5','71','41',null,null,'A');
Insert into JKRAJPOP.MAINTENANCE (MAINTENANCEID,MAKE,MODEL,MILES,SERVICE1,SERVICE2,SERVICE3,SERVICE4,SERVICE5,SERVICE6,MAINTENANCETYPE) values ('M0008','Nissan','Altima',25000,'17','125',null,null,null,null,'B');
Insert into JKRAJPOP.MAINTENANCE (MAINTENANCEID,MAKE,MODEL,MILES,SERVICE1,SERVICE2,SERVICE3,SERVICE4,SERVICE5,SERVICE6,MAINTENANCETYPE) values ('M0009','Nissan','Altima',50000,'95','23','83','89',null,null,'C');
Insert into JKRAJPOP.MAINTENANCE (MAINTENANCEID,MAKE,MODEL,MILES,SERVICE1,SERVICE2,SERVICE3,SERVICE4,SERVICE5,SERVICE6,MAINTENANCETYPE) values ('M0010','Nissan','Rogue',10000,'54','6','84','72','18','42','A');
Insert into JKRAJPOP.MAINTENANCE (MAINTENANCEID,MAKE,MODEL,MILES,SERVICE1,SERVICE2,SERVICE3,SERVICE4,SERVICE5,SERVICE6,MAINTENANCETYPE) values ('M0011','Nissan','Rogue',37000,'96','126','90',null,null,null,'B');
Insert into JKRAJPOP.MAINTENANCE (MAINTENANCEID,MAKE,MODEL,MILES,SERVICE1,SERVICE2,SERVICE3,SERVICE4,SERVICE5,SERVICE6,MAINTENANCETYPE) values ('M0012','Nissan','Rogue',70000,'24','12',null,null,null,null,'C');
Insert into JKRAJPOP.MAINTENANCE (MAINTENANCEID,MAKE,MODEL,MILES,SERVICE1,SERVICE2,SERVICE3,SERVICE4,SERVICE5,SERVICE6,MAINTENANCETYPE) values ('M0013','Honda','Accord',15000,'52','4','70','40',null,null,'A');
Insert into JKRAJPOP.MAINTENANCE (MAINTENANCEID,MAKE,MODEL,MILES,SERVICE1,SERVICE2,SERVICE3,SERVICE4,SERVICE5,SERVICE6,MAINTENANCETYPE) values ('M0014','Honda','Accord',37000,'16','124','88',null,null,null,'B');
Insert into JKRAJPOP.MAINTENANCE (MAINTENANCEID,MAKE,MODEL,MILES,SERVICE1,SERVICE2,SERVICE3,SERVICE4,SERVICE5,SERVICE6,MAINTENANCETYPE) values ('M0015','Honda','Accord',67000,'94','22','82',null,null,null,'C');
Insert into JKRAJPOP.MAINTENANCE (MAINTENANCEID,MAKE,MODEL,MILES,SERVICE1,SERVICE2,SERVICE3,SERVICE4,SERVICE5,SERVICE6,MAINTENANCETYPE) values ('M0016','Honda','Civic',14000,'51','15','39',null,null,null,'A');
Insert into JKRAJPOP.MAINTENANCE (MAINTENANCEID,MAKE,MODEL,MILES,SERVICE1,SERVICE2,SERVICE3,SERVICE4,SERVICE5,SERVICE6,MAINTENANCETYPE) values ('M0017','Honda','Civic',29000,'3','69','21','123','87',null,'B');
Insert into JKRAJPOP.MAINTENANCE (MAINTENANCEID,MAKE,MODEL,MILES,SERVICE1,SERVICE2,SERVICE3,SERVICE4,SERVICE5,SERVICE6,MAINTENANCETYPE) values ('M0018','Honda','Civic',44000,'93','81',null,null,null,null,'C');
--------------------------------------------------------
--  DDL for Index MAINTENANCE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JKRAJPOP"."MAINTENANCE_PK" ON "JKRAJPOP"."MAINTENANCE" ("MAINTENANCEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MAINTENANCE
--------------------------------------------------------

  ALTER TABLE "JKRAJPOP"."MAINTENANCE" ADD CONSTRAINT "MAINTENANCE_PK" PRIMARY KEY ("MAINTENANCEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "JKRAJPOP"."MAINTENANCE" MODIFY ("MAINTENANCEID" NOT NULL ENABLE);
 
  ALTER TABLE "JKRAJPOP"."MAINTENANCE" MODIFY ("MAKE" NOT NULL ENABLE);
 
  ALTER TABLE "JKRAJPOP"."MAINTENANCE" MODIFY ("MODEL" NOT NULL ENABLE);
 
  ALTER TABLE "JKRAJPOP"."MAINTENANCE" MODIFY ("MILES" NOT NULL ENABLE);
 
  ALTER TABLE "JKRAJPOP"."MAINTENANCE" MODIFY ("MAINTENANCETYPE" NOT NULL ENABLE);
