--------------------------------------------------------
--  File created - Tuesday-November-20-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SERVICECENTER
--------------------------------------------------------

  CREATE TABLE "JKRAJPOP"."SERVICECENTER" 
   (	"ADDRESS" VARCHAR2(255 BYTE), 
	"SERVICECENTERID" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(255 BYTE), 
	"TELNO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into JKRAJPOP.SERVICECENTER
SET DEFINE OFF;
Insert into JKRAJPOP.SERVICECENTER (ADDRESS,SERVICECENTERID,NAME,TELNO) values ('437 Fayetteville St., Raleigh, NC 27601','S0001','Downtown Auto Care',18008999999);
Insert into JKRAJPOP.SERVICECENTER (ADDRESS,SERVICECENTERID,NAME,TELNO) values ('201 N Tryon St, Charlotte, NC 28202','S0002','Express Auto Shop',17043331555);
--------------------------------------------------------
--  DDL for Index SERVICECENTER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JKRAJPOP"."SERVICECENTER_PK" ON "JKRAJPOP"."SERVICECENTER" ("SERVICECENTERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SERVICECENTER
--------------------------------------------------------

  ALTER TABLE "JKRAJPOP"."SERVICECENTER" ADD CONSTRAINT "SERVICECENTER_PK" PRIMARY KEY ("SERVICECENTERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "JKRAJPOP"."SERVICECENTER" MODIFY ("ADDRESS" NOT NULL ENABLE);
 
  ALTER TABLE "JKRAJPOP"."SERVICECENTER" MODIFY ("SERVICECENTERID" NOT NULL ENABLE);
 
  ALTER TABLE "JKRAJPOP"."SERVICECENTER" MODIFY ("NAME" NOT NULL ENABLE);
