--------------------------------------------------------
--  File created - Tuesday-November-20-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ORDERS
--------------------------------------------------------

  CREATE TABLE "JKRAJPOP"."ORDERS" 
   (	"ORDERID" VARCHAR2(20 BYTE), 
	"PARTID" VARCHAR2(20 BYTE), 
	"EXPECTEDDELIVERY" DATE, 
	"ACTUALDELIVERY" DATE, 
	"QUANTITY" NUMBER(*,0), 
	"DESTINATION" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"ORDERPLACEMENT" DATE, 
	"ORIGIN" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into JKRAJPOP.ORDERS
SET DEFINE OFF;
Insert into JKRAJPOP.ORDERS (ORDERID,PARTID,EXPECTEDDELIVERY,ACTUALDELIVERY,QUANTITY,DESTINATION,STATUS,ORDERPLACEMENT,ORIGIN) values ('1','7',to_date('13-JUN-14','DD-MON-RR'),to_date('18-JUN-14','DD-MON-RR'),5,'S0001','Complete',to_date('09-JUN-14','DD-MON-RR'),'D0001');
Insert into JKRAJPOP.ORDERS (ORDERID,PARTID,EXPECTEDDELIVERY,ACTUALDELIVERY,QUANTITY,DESTINATION,STATUS,ORDERPLACEMENT,ORIGIN) values ('2','56',to_date('21-SEP-15','DD-MON-RR'),to_date('21-SEP-15','DD-MON-RR'),5,'S0001','Complete',to_date('16-SEP-15','DD-MON-RR'),'D0002');
Insert into JKRAJPOP.ORDERS (ORDERID,PARTID,EXPECTEDDELIVERY,ACTUALDELIVERY,QUANTITY,DESTINATION,STATUS,ORDERPLACEMENT,ORIGIN) values ('3','32',to_date('11-FEB-16','DD-MON-RR'),to_date('11-FEB-16','DD-MON-RR'),5,'S0002','Complete',to_date('10-FEB-16','DD-MON-RR'),'S0001');
Insert into JKRAJPOP.ORDERS (ORDERID,PARTID,EXPECTEDDELIVERY,ACTUALDELIVERY,QUANTITY,DESTINATION,STATUS,ORDERPLACEMENT,ORIGIN) values ('4','24',to_date('10-AUG-17','DD-MON-RR'),to_date('11-AUG-17','DD-MON-RR'),4,'S0001','Complete',to_date('09-AUG-17','DD-MON-RR'),'S0002');
Insert into JKRAJPOP.ORDERS (ORDERID,PARTID,EXPECTEDDELIVERY,ACTUALDELIVERY,QUANTITY,DESTINATION,STATUS,ORDERPLACEMENT,ORIGIN) values ('5','1',to_date('05-OCT-18','DD-MON-RR'),to_date('05-OCT-18','DD-MON-RR'),6,'S0002','Complete',to_date('04-OCT-18','DD-MON-RR'),'S0001');
Insert into JKRAJPOP.ORDERS (ORDERID,PARTID,EXPECTEDDELIVERY,ACTUALDELIVERY,QUANTITY,DESTINATION,STATUS,ORDERPLACEMENT,ORIGIN) values ('6','18',to_date('01-NOV-18','DD-MON-RR'),to_date('05-NOV-18','DD-MON-RR'),5,'S0001','Complete',to_date('26-OCT-18','DD-MON-RR'),'D0001');
Insert into JKRAJPOP.ORDERS (ORDERID,PARTID,EXPECTEDDELIVERY,ACTUALDELIVERY,QUANTITY,DESTINATION,STATUS,ORDERPLACEMENT,ORIGIN) values ('7','56',to_date('14-NOV-18','DD-MON-RR'),null,7,'S0002','Pending',to_date('09-NOV-18','DD-MON-RR'),'D0002');
Insert into JKRAJPOP.ORDERS (ORDERID,PARTID,EXPECTEDDELIVERY,ACTUALDELIVERY,QUANTITY,DESTINATION,STATUS,ORDERPLACEMENT,ORIGIN) values ('8','5',to_date('14-NOV-18','DD-MON-RR'),null,12,'S0002','Pending',to_date('07-NOV-18','DD-MON-RR'),'D0001');
Insert into JKRAJPOP.ORDERS (ORDERID,PARTID,EXPECTEDDELIVERY,ACTUALDELIVERY,QUANTITY,DESTINATION,STATUS,ORDERPLACEMENT,ORIGIN) values ('9','17',to_date('14-NOV-18','DD-MON-RR'),null,6,'S0002','Pending',to_date('08-NOV-18','DD-MON-RR'),'D0001');
Insert into JKRAJPOP.ORDERS (ORDERID,PARTID,EXPECTEDDELIVERY,ACTUALDELIVERY,QUANTITY,DESTINATION,STATUS,ORDERPLACEMENT,ORIGIN) values ('10','38',to_date('14-NOV-18','DD-MON-RR'),null,5,'S0002','Pending',to_date('08-NOV-18','DD-MON-RR'),'D0001');
Insert into JKRAJPOP.ORDERS (ORDERID,PARTID,EXPECTEDDELIVERY,ACTUALDELIVERY,QUANTITY,DESTINATION,STATUS,ORDERPLACEMENT,ORIGIN) values ('11','11',to_date('14-NOV-18','DD-MON-RR'),null,5,'S0002','Pending',to_date('08-NOV-18','DD-MON-RR'),'D0002');
--------------------------------------------------------
--  DDL for Index SYS_C00485790
--------------------------------------------------------

  CREATE UNIQUE INDEX "JKRAJPOP"."SYS_C00485790" ON "JKRAJPOP"."ORDERS" ("ORDERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger ORDERS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "JKRAJPOP"."ORDERS_TRG" 
BEFORE INSERT ON ORDERS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ORDERID IS NULL THEN
      SELECT ORDERS_SEQ.NEXTVAL INTO :NEW.ORDERID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "JKRAJPOP"."ORDERS_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "JKRAJPOP"."ORDERS" ADD PRIMARY KEY ("ORDERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
