--------------------------------------------------------
--  File created - Tuesday-November-20-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "JKRAJPOP"."CUSTOMER" 
   (	"NAME" VARCHAR2(255 BYTE), 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"PHONENUMBER" NUMBER, 
	"EMAIL" VARCHAR2(40 BYTE), 
	"SERVICECENTERID" VARCHAR2(20 BYTE), 
	"CUSTOMERID" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into JKRAJPOP.CUSTOMER
SET DEFINE OFF;
Insert into JKRAJPOP.CUSTOMER (NAME,ADDRESS,PHONENUMBER,EMAIL,SERVICECENTERID,CUSTOMERID,PASSWORD) values ('Tom Cruise','203, Park St, Raleigh, NC - 27603',1234567890,'ethanhunt@gmail.com','S0001','1001','Tom');
Insert into JKRAJPOP.CUSTOMER (NAME,ADDRESS,PHONENUMBER,EMAIL,SERVICECENTERID,CUSTOMERID,PASSWORD) values ('Robert Downey Jr.','12-A, High St, Raleigh, NC - 27605',9989877791,'jarvis@gmail.com','S0001','1002','Robert');
Insert into JKRAJPOP.CUSTOMER (NAME,ADDRESS,PHONENUMBER,EMAIL,SERVICECENTERID,CUSTOMERID,PASSWORD) values ('Taylor Swift','2A, 3rd Ave, Charlotte, NC - 28134',8179827199,'lovestory@gmail.com','S0002','1003','Taylor');
Insert into JKRAJPOP.CUSTOMER (NAME,ADDRESS,PHONENUMBER,EMAIL,SERVICECENTERID,CUSTOMERID,PASSWORD) values ('Serena Williams','90, Gorman St, Charlotte, NC - 28201',8714791879,'venus@gmail.com','S0003','1004','Williams');
--------------------------------------------------------
--  DDL for Index CUSTOMER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JKRAJPOP"."CUSTOMER_PK" ON "JKRAJPOP"."CUSTOMER" ("CUSTOMERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "JKRAJPOP"."CUSTOMER" ADD CONSTRAINT "CUSTOMER_PK" PRIMARY KEY ("CUSTOMERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "JKRAJPOP"."CUSTOMER" MODIFY ("CUSTOMERID" NOT NULL ENABLE);
 
  ALTER TABLE "JKRAJPOP"."CUSTOMER" MODIFY ("PASSWORD" NOT NULL ENABLE);
