--------------------------------------------------------
--  File created - Tuesday-November-20-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SERVICEHISTORY
--------------------------------------------------------

  CREATE TABLE "JKRAJPOP"."SERVICEHISTORY" 
   (	"CUSTOMERID" VARCHAR2(20 BYTE), 
	"LICENSEPLATE" VARCHAR2(20 BYTE), 
	"SERVICEDATE" DATE, 
	"TYPEOFSERVICE" VARCHAR2(200 BYTE), 
	"STARTTIME" VARCHAR2(20 BYTE), 
	"ENDTIME" VARCHAR2(20 BYTE), 
	"MECHANICNAME" VARCHAR2(20 BYTE), 
	"SENDDATE" DATE, 
	"SERVICEHISTORY" NUMBER, 
	"DIAGNOSIS" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into JKRAJPOP.SERVICEHISTORY
SET DEFINE OFF;
Insert into JKRAJPOP.SERVICEHISTORY (CUSTOMERID,LICENSEPLATE,SERVICEDATE,TYPEOFSERVICE,STARTTIME,ENDTIME,MECHANICNAME,SENDDATE,SERVICEHISTORY,DIAGNOSIS) values ('1001','AHS-3132',to_date('28-JAN-18','DD-MON-RR'),'A','12:00','17:00','Peter Fitzpatrick',to_date('28-JAN-18','DD-MON-RR'),6,null);
Insert into JKRAJPOP.SERVICEHISTORY (CUSTOMERID,LICENSEPLATE,SERVICEDATE,TYPEOFSERVICE,STARTTIME,ENDTIME,MECHANICNAME,SENDDATE,SERVICEHISTORY,DIAGNOSIS) values ('1002','IRM-1212',to_date('11-FEB-18','DD-MON-RR'),'A','08:30','17:00','Eric Fowler',to_date('11-FEB-18','DD-MON-RR'),7,null);
Insert into JKRAJPOP.SERVICEHISTORY (CUSTOMERID,LICENSEPLATE,SERVICEDATE,TYPEOFSERVICE,STARTTIME,ENDTIME,MECHANICNAME,SENDDATE,SERVICEHISTORY,DIAGNOSIS) values ('1002','IRM-1212',to_date('10-DEC-17','DD-MON-RR'),'C','09:30','17:00','Eric Fowler',to_date('10-DEC-17','DD-MON-RR'),8,null);
Insert into JKRAJPOP.SERVICEHISTORY (CUSTOMERID,LICENSEPLATE,SERVICEDATE,TYPEOFSERVICE,STARTTIME,ENDTIME,MECHANICNAME,SENDDATE,SERVICEHISTORY,DIAGNOSIS) values ('1002','IRM-1212',to_date('20-JAN-17','DD-MON-RR'),'B','10:00','17:00','Eric Fowler',to_date('20-JAN-17','DD-MON-RR'),9,null);
Insert into JKRAJPOP.SERVICEHISTORY (CUSTOMERID,LICENSEPLATE,SERVICEDATE,TYPEOFSERVICE,STARTTIME,ENDTIME,MECHANICNAME,SENDDATE,SERVICEHISTORY,DIAGNOSIS) values ('1003','DEL-8888',to_date('11-FEB-18','DD-MON-RR'),'A','08:30','17:00','Rickie Henderson',to_date('11-FEB-18','DD-MON-RR'),10,null);
Insert into JKRAJPOP.SERVICEHISTORY (CUSTOMERID,LICENSEPLATE,SERVICEDATE,TYPEOFSERVICE,STARTTIME,ENDTIME,MECHANICNAME,SENDDATE,SERVICEHISTORY,DIAGNOSIS) values ('1003','DEL-8888',to_date('05-NOV-16','DD-MON-RR'),'Repair','09:00','17:00','Charles Pudilo',to_date('05-NOV-16','DD-MON-RR'),11,'DG036');
Insert into JKRAJPOP.SERVICEHISTORY (CUSTOMERID,LICENSEPLATE,SERVICEDATE,TYPEOFSERVICE,STARTTIME,ENDTIME,MECHANICNAME,SENDDATE,SERVICEHISTORY,DIAGNOSIS) values ('1004','P11-212A',to_date('01-SEP-17','DD-MON-RR'),'B','09:00','17:00','Dustin Esparza',to_date('01-SEP-17','DD-MON-RR'),12,null);
Insert into JKRAJPOP.SERVICEHISTORY (CUSTOMERID,LICENSEPLATE,SERVICEDATE,TYPEOFSERVICE,STARTTIME,ENDTIME,MECHANICNAME,SENDDATE,SERVICEHISTORY,DIAGNOSIS) values ('1004','P11-212A',to_date('15-JUN-14','DD-MON-RR'),'A','08:30','17:00','James Rivera',to_date('15-JUN-14','DD-MON-RR'),13,null);
Insert into JKRAJPOP.SERVICEHISTORY (CUSTOMERID,LICENSEPLATE,SERVICEDATE,TYPEOFSERVICE,STARTTIME,ENDTIME,MECHANICNAME,SENDDATE,SERVICEHISTORY,DIAGNOSIS) values ('1004','WIM-BLE5',to_date('11-NOV-16','DD-MON-RR'),'A','08:30','17:00','James Rivera',to_date('11-NOV-16','DD-MON-RR'),14,null);
Insert into JKRAJPOP.SERVICEHISTORY (CUSTOMERID,LICENSEPLATE,SERVICEDATE,TYPEOFSERVICE,STARTTIME,ENDTIME,MECHANICNAME,SENDDATE,SERVICEHISTORY,DIAGNOSIS) values ('1004','WIM-BLE5',to_date('02-JAN-16','DD-MON-RR'),'Repair','14:00','17:00','Charles Pudilo',to_date('02-JAN-16','DD-MON-RR'),15,'DG026');
Insert into JKRAJPOP.SERVICEHISTORY (CUSTOMERID,LICENSEPLATE,SERVICEDATE,TYPEOFSERVICE,STARTTIME,ENDTIME,MECHANICNAME,SENDDATE,SERVICEHISTORY,DIAGNOSIS) values ('1004','WIM-BLE5',to_date('30-SEP-15','DD-MON-RR'),'Repair','11:00','17:00','Charles Pudilo',to_date('30-SEP-15','DD-MON-RR'),16,'DG002');
Insert into JKRAJPOP.SERVICEHISTORY (CUSTOMERID,LICENSEPLATE,SERVICEDATE,TYPEOFSERVICE,STARTTIME,ENDTIME,MECHANICNAME,SENDDATE,SERVICEHISTORY,DIAGNOSIS) values ('1001','XYZ-5643',to_date('10-SEP-18','DD-MON-RR'),'C','10:00','17:00','Jacob Gloss',to_date('10-SEP-18','DD-MON-RR'),1,null);
Insert into JKRAJPOP.SERVICEHISTORY (CUSTOMERID,LICENSEPLATE,SERVICEDATE,TYPEOFSERVICE,STARTTIME,ENDTIME,MECHANICNAME,SENDDATE,SERVICEHISTORY,DIAGNOSIS) values ('1001','XYZ-5643',to_date('25-FEB-18','DD-MON-RR'),'B','09:00','17:00','Eric Fowler',to_date('25-FEB-18','DD-MON-RR'),2,null);
Insert into JKRAJPOP.SERVICEHISTORY (CUSTOMERID,LICENSEPLATE,SERVICEDATE,TYPEOFSERVICE,STARTTIME,ENDTIME,MECHANICNAME,SENDDATE,SERVICEHISTORY,DIAGNOSIS) values ('1001','XYZ-5643',to_date('15-OCT-17','DD-MON-RR'),'A','08:00','17:00','Anthony Freeman',to_date('15-OCT-17','DD-MON-RR'),3,null);
Insert into JKRAJPOP.SERVICEHISTORY (CUSTOMERID,LICENSEPLATE,SERVICEDATE,TYPEOFSERVICE,STARTTIME,ENDTIME,MECHANICNAME,SENDDATE,SERVICEHISTORY,DIAGNOSIS) values ('1001','AHS-3132',to_date('06-AUG-18','DD-MON-RR'),'Repair','08:00','17:00','Roland Richmond',to_date('06-AUG-18','DD-MON-RR'),4,'DG014');
Insert into JKRAJPOP.SERVICEHISTORY (CUSTOMERID,LICENSEPLATE,SERVICEDATE,TYPEOFSERVICE,STARTTIME,ENDTIME,MECHANICNAME,SENDDATE,SERVICEHISTORY,DIAGNOSIS) values ('1001','AHS-3132',to_date('15-MAY-18','DD-MON-RR'),'B','10:30','17:00','Peter Fitzpatrick',to_date('15-MAY-18','DD-MON-RR'),5,null);
--------------------------------------------------------
--  DDL for Index SERVICEHISTORY_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "JKRAJPOP"."SERVICEHISTORY_PK1" ON "JKRAJPOP"."SERVICEHISTORY" ("SERVICEHISTORY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SERVICEHISTORY
--------------------------------------------------------

  ALTER TABLE "JKRAJPOP"."SERVICEHISTORY" ADD CONSTRAINT "SERVICEHISTORY_PK" PRIMARY KEY ("SERVICEHISTORY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "JKRAJPOP"."SERVICEHISTORY" MODIFY ("CUSTOMERID" NOT NULL ENABLE);
 
  ALTER TABLE "JKRAJPOP"."SERVICEHISTORY" MODIFY ("LICENSEPLATE" NOT NULL ENABLE);
 
  ALTER TABLE "JKRAJPOP"."SERVICEHISTORY" MODIFY ("SERVICEHISTORY" NOT NULL ENABLE);
